### ISSUE TITLE
No button to close, minimize or resize at top

### ISSUE THREAD

**Issue by machitgarha** [mehdiraized/npmax#1]
At the top, three buttons to do things mentioned in the title are disappeared. This means I cannot directly minimize the application, for example. Obviously, shortcuts work (e.g. Alt + F4 closes the app).

## Steps to Reproduce

Nothing; just open the application.

## Environment

OS: Fedora 32 (Workstation)
Kernel: Linux 5.7.8

**Comment by mehdiraized** [comment]
Thanks for send feedback.
This problem is solved in v0.1.0

**Comment by machitgarha** [comment]
Closing this issue, as it should be under #2.
